//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JZ.Test.JZWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JZWCF.IJZWCF")]
    public interface IJZWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJZWCF/PostSource", ReplyAction="http://tempuri.org/IJZWCF/PostSourceResponse")]
        string PostSource(string strJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJZWCF/PostSource", ReplyAction="http://tempuri.org/IJZWCF/PostSourceResponse")]
        System.Threading.Tasks.Task<string> PostSourceAsync(string strJson);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJZWCFChannel : JZ.Test.JZWCF.IJZWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JZWCFClient : System.ServiceModel.ClientBase<JZ.Test.JZWCF.IJZWCF>, JZ.Test.JZWCF.IJZWCF {
        
        public JZWCFClient() {
        }
        
        public JZWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JZWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JZWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JZWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PostSource(string strJson) {
            return base.Channel.PostSource(strJson);
        }
        
        public System.Threading.Tasks.Task<string> PostSourceAsync(string strJson) {
            return base.Channel.PostSourceAsync(strJson);
        }
    }
}
