//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace JZ.Models
{
    /// <summary>	
    /// 数据表实体类： (Sys_UserInfo)
    /// </summary>
    [SugarTable("Sys_UserInfo")][Serializable]
    public partial class Sys_UserInfo:BaseEntity
    {       
        private string _UserID ;
        /// <summary>
        ///  编号
        /// </summary>
        
        public  string UserID 
        {
            get
            {
            	return this._UserID;
            }
            set
            {
            	if (this._UserID != value)
            	{
            		base.SetValueCall("UserID", this._UserID);
            	}
            	this._UserID = value;
            }
         }
        private string _UserCode ;
        /// <summary>
        ///  账号
        /// </summary>
        
        public  string UserCode 
        {
            get
            {
            	return this._UserCode;
            }
            set
            {
            	if (this._UserCode != value)
            	{
            		base.SetValueCall("UserCode", this._UserCode);
            	}
            	this._UserCode = value;
            }
         }
        private string _UserName ;
        /// <summary>
        ///  名称
        /// </summary>
        
        public  string UserName 
        {
            get
            {
            	return this._UserName;
            }
            set
            {
            	if (this._UserName != value)
            	{
            		base.SetValueCall("UserName", this._UserName);
            	}
            	this._UserName = value;
            }
         }
        private string _UserPassword ;
        /// <summary>
        ///  密码
        /// </summary>
        
        public  string UserPassword 
        {
            get
            {
            	return this._UserPassword;
            }
            set
            {
            	if (this._UserPassword != value)
            	{
            		base.SetValueCall("UserPassword", this._UserPassword);
            	}
            	this._UserPassword = value;
            }
         }
        private int _UserLevel ;
        /// <summary>
        ///  用户等级，越小级别越高
        /// </summary>
        
        public  int UserLevel 
        {
            get
            {
            	return this._UserLevel;
            }
            set
            {
            	if (this._UserLevel != value)
            	{
            		base.SetValueCall("UserLevel", this._UserLevel);
            	}
            	this._UserLevel = value;
            }
         }
 
    }
}

